<#
The MIT License (MIT)

Copyright (c) 2015 Objectivity Bespoke Software Specialists

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
#>

function ConvertTo-EnhancedHTMLFragmentRickshawChart {

    <#
    .SYNOPSIS
    Creates a HTML fragment containing a Rickshaw chart (based on Javascript data generated by ConvertTo-EnhancedHTMLFragmentRickshawJavascriptData).

    .PARAMETER JavascriptDataVariableName
    Name of Javascript variable created by ConvertTo-EnhancedHTMLFragmentRickshawJavascriptData.

    .PARAMETER JavascriptTestTimeThresholdDataVariableName
    Name of Javascript variable with hashtable containing test time thresholds.

    .PARAMETER Width
    Chart width.

    .PARAMETER Height
    Chart height.

    .LINK
    ConvertTo-EnhancedHTMLFragmentRickshawJavascriptData

    .EXAMPLE
    $htmlChart = ConvertTo-EnhancedHTMLFragmentRickshawChart -JavascriptDataVariableName 'TestData'
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [Parameter(Mandatory=$true)]
        [string]
        $JavascriptDataVariableName,

        [Parameter(Mandatory=$true)]
        [string]
        $JavascriptTestTimeThresholdDataVariableName,

        [Parameter(Mandatory=$false)]
        [int]
        $Width = 900,

        [Parameter(Mandatory=$false)]
        [int]
        $Height = 500
    )

    $javascriptFiles = Get-ChildItem -Path "$PSScriptRoot\TestTrendJavascript\*.js" | Get-Content -ReadCount 0 | Out-String
   
    $result = @"

<div id="options">
    <form id="chartFilterForm">
        <label>Number of last builds: <input id="testHistoryNumber" type="number" min="0" value="0"/></label>
        <label>Include build numbers: <input id="includeBuilds" type="text" /></label>
        <label>Exclude build numbers: <input id="excludeBuilds" type="text" /></label>
        <label>Test name regex: <input id="testNameRegex" type="text" /></label>
        <label>Relative to build: <input id="relativeToBuild" type="text" /></label>
        <input id="relativeToBuildPercent" type="checkbox">Percent</input>
        <label>Chart type:
        <select id="chartRenderer">
            <option value="line">Line</option>
            <option value="scatterplot">Scatter</option>
            <option value="area">Area</option>
            <option value="bar">Bar</option>
        </select>
        </label>
        <input id="showFailedBuilds" type="checkbox" checked>Show failed</input>
        <input type="submit" value="Update" action="javascript:void(0)" />
    </form>
</div>

<div id="contentChart">
    <div id="legend"></div>
    <div id="chartContainer">
        <div id="chart"></div>
        <div id="preview"></div>
    </div>
</div>
<div id="tableContainer">
</div>

<script type="text/javascript">

var dataModel = function() {
    var self = {
        originalChartData: ${JavascriptDataVariableName}.reverse(),
        chartData: null,
        testTimeThresholdData: ${JavascriptTestTimeThresholdDataVariableName},
        width: $Width,
        height: $Height,

        hasTestTimeThresholdData: function() {
            return (self.testTimeThresholdData != null && Object.getOwnPropertyNames(self.testTimeThresholdData).length > 0);
        }
    };

    return self;
}();
"@ + $javascriptFiles + @"
jQuery('#chartFilterForm').submit(function (event) {
    event.preventDefault();
    mainController.showGraphAndTable();
});

jQuery(document).ready(function() {
    mainController.init(dataModel, inputModel, graphModel, tableModel);
    mainController.showGraphAndTable();
});
</script>
"@

    return $result
}